open-spaced-repetition/py-fsrs

.gitignore
README.md
pyproject.toml
src/fsrs/__init__.py
src/fsrs/fsrs.py
src/fsrs/models.py
tests/test_fsrs.py

PR to address issue #28 
- New card objects when created are now timezone-aware in addition to being UTC
- When cards are repeated, the time value they receive must be timezone-aware and UTC
- Updated the README with new example
- Added new tests and modified the old one
- Bumped major version from 1.2.0 -> 2.0.0 since these are breaking changes
For developers using previous versions of py-fsrs, they can update an old card object by using the following code:
```python
import datetime
card_object.due = card_object.due.replace(tzinfo=datetime.timezone.utc)
if hasattr(card_object, 'last_review'):
card_object.last_review = card_object.last_review.replace(tzinfo=datetime.timezone.utc)
```
Let me know if there are any questions or issues 👍

v2.0.0 - update cards to be timezone aware

---

pyproject.toml
src/fsrs/__init__.py
src/fsrs/models.py
tests/test_fsrs.py

PR to address issue #32 
- Added a `.to_dict()` method to the Card class so that Card objects can now be represented as json-serializable dictionaries for storage in databases
```python
card_obj = Card()
card_dict = card_obj.to_dict()
card_json = json.dumps(card_dict)
```
- Added a static `.from_dict()` method to the Card class so that data from previously serialized card objects can be used to reconstruct new Card objects
```python
new_card_obj = Card.from_dict(card_dict)
```
- Added `test_serialize` in tests/test_fsrs.py to test this feature
- Bumped version from 2.0.0 -> 2.1.0 as this feature is backward compatible
Let me know if there are any questions or issues 👍

v2.1.0 - make Card objects JSON serializable

---

src/fsrs/models.py

fix a typo: its a review_log, not Review_log

Use lower case for attribute in SchedulingInfo

---

README.md
pyproject.toml
src/fsrs/__init__.py
src/fsrs/fsrs.py
tests/test_fsrs.py

I modified the `repeat` function to take a default argument for the datetime variable thus making it entirely optional for developers to create and pass a datetime object if they want to repeat a card.
Now instead of having to do
```python
scheduling_cards = f.repeat(card_object, datetime.now(timezone.utc))
```
developers can instead write
```python
scheduling_cards = f.repeat(card_object)
```
if they want to repeat the card 'now'.
I also did the following:
1. Bumped minor version: 2.1.1 -> 2.2.0
2. Added a test for this new functionality
3. Modified the README's `repeat` function example to use the default parameter.
Let me know if this sounds good, or if there are any issues or questions 👍

add default argument to repeat function

---

pyproject.toml
src/fsrs/__init__.py
src/fsrs/models.py
tests/test_fsrs.py

I made ReviewLog objects JSON-serializable so that these logs can be easily stored in databases. The changes are very similar to the changes made in #33 for Card objects.
Changes:
- Added `.to_dict()` method to ReviewLog for serialization
- Added static `.from_dict()` method for deserialization
- Added a new test: `test_ReviewLog_serialize` to test the serialization
- Bumped from version 2.2.1 -> 2.3.0

make ReviewLog objects JSON-serializable

---

README.md
pyproject.toml
src/fsrs/__init__.py
src/fsrs/fsrs.py
tests/test_fsrs.py

I added a new function `review_card` to the FSRS class to make reviewing cards more straightforward.
Now instead of having to review cards like:
```python
rating = Rating.Good
scheduling_cards = f.repeat(card)
card = scheduling_cards[rating].card
review_log = scheduling_cards[rating].review_log
```
Developers can write:
```python
rating = Rating.Good
card, review_log = f.review_card(card, rating)
```
Let me know if this level of abstraction is welcome 👍
Other changes:
- Bumped version from 2.3.0 -> 2.4.0
- Added test to for the `review_card` function
- Updated the Quickstart section in the README to use `review_card`

feat/add review_card function

---

README.md
pyproject.toml
src/fsrs/fsrs.py
src/fsrs/models.py
tests/test_fsrs.py

I added custom arguments to the the FSRS and Parameter classes so that developers can specify their own custom weights, desired retention and maximum interval.
In all:
- Modified the `__init__` of the FSRS and Parameter classes
- Added an additional test to demonstrate that this functionality works
- Updated the README to give an example of how to implement this functionality under the Usage section.
Let me know if there's any issues or questions 👍

add custom args to FSRS class

---

pyproject.toml
src/fsrs/models.py

serializing and deserializing a dictionary (for example by storing it in a redis db) saves the ints and floats as string.

Cast integer and Float values when reading from dict

---

CONTRIBUTING.md
mypy.ini
pyproject.toml
pytest.ini

I moved the `pytest.ini` and `mypy.ini` files into `pyproject.toml` to reduce clutter in the repo.
I also added instructions in CONTRIBUTING for how contributors can run the mypy type-checker so that their contributions can pass the mypy workflow added in #48. 
I will say that I want to be cautious about adding too much in the way of contributing though. We currently have checks for linting, type-checking and tests and I'm not sure if it's a good idea to add too much more stuff since it might discourage new contributors.
Anyways, lmk if you have any questions or issues 👍

mypy contributing

---

README.md
src/fsrs/fsrs.py

I went and removed the wildcard imports from both the `fsrs.py` module and the `README.md` file as it's generally considered better practice not to use wildcard imports.
Let me know if there are any questions/issues

remove wildcard imports

---

src/fsrs/fsrs.py
src/fsrs/models.py

I went and added some more type annotations to the source code to make it a bit easier to grok. 
Additionally, because the pyproject.toml specifies that py-fsrs requires at least python 3.9, I replaced the `Tuple` and `Dict` type annotations with `tuple` and `dict` type annotations, which are equivalent, but don't require an import statement.
Let me know if there are any issues/questions

add more type annotation

---

pyproject.toml
src/fsrs/models.py
tests/test_fsrs.py

Currently, you can only get a card’s retrievability when it’s in the Review state. I thought it would be good enhancement if you could also compute the retrievability for cards in the other states as well.
Changes:
- Compute retrievability for Learning and Relearning cards the same way it's computed for Review cards
- New cards have 0 retrievability
- Rationale: given that new cards have S=0, then for t>0, R(t,S) -> 0 as S -> 0(+)
- Made the datetime argument optional for the `get_retrievability` function.
- If the function is invoked without a given datetime, the datetime defaults to `datetime.now(timezone.utc)` similar to the Card class's `__init__` method or the FSRS class's `review_card` method.
- Bump minor version: 3.0.0 -> 3.1.0
- Add test: `test_retrievability` to demonstrate this …

compute retrievability for all states

---

.github/workflows/ruff.yml

The previous unofficial ruff gh action that we were using is no longer maintained: https://github.com/ChartBoost/ruff-action.
I switched our ruff gh action to the official version: https://github.com/astral-sh/ruff-action
Let me know if there are any questions.

Switch to official ruff gh action

---

src/fsrs/fsrs.py
tests/test_fsrs.py

In #64, I added fuzzing, but this was only for Review-state cards that had been given a succesful rating of Hard, Good or Easy. I'm thinking it would also make sense to fuzz any interval that is not a user-defined learning or a relearning step.
In this PR, I made it so that the intervals of cards graduating from the re/learning steps now get fuzzed. Also, I made it so that Review-state cards, when rated Again with no relearning steps specified in the scheduler now also get fuzzed.
Let me know if this makes sense or if you have any questions 👍

Fuzz more intervals

---

pyproject.toml
src/fsrs/fsrs.py
tests/test_fsrs.py

The lines thresholding the difficulty between 1 and 10 were causing difficulty to become an integer, which then caused it to fail a type check later.
This change:
1. fixes the thresholding of difficulty to be between 1.0 and 10.0
2. adds a test of multiple successful reviews in quick succession to hit this threshold

Fixes type bug where difficulty became an int if it exceeded the thresholds

---

CONTRIBUTING.md
pyproject.toml

Py-FSRS uses Ruff for linting and formatting, mypy for type checking and pytest for unit tests. Currently, when developing locally, each of these dependencies must be installed individually.
To make things a bit more clean, I added optional `dev` dependencies to the pyproject.toml so that installing these dependencies (along with fsrs itself) is more straightforward with just
```
pip install -e ".[dev]"
```
I also updated CONTRIBUTING.md to include instructions on how to install the dev dependencies.

Add optional dev dependencies to pyproject.toml

---

fsrs/fsrs.py

`math.exp` and `math.pow` can lead to potential issues given the way that they perform computations under the hood (i.e., `math.e ** 2 != math.exp(2)` also, see [here](https://github.com/pytorch/pytorch/issues/143071) and [here](https://github.com/pytorch/pytorch/pull/143261)).
Given this, I've swapped out occurences of `math.exp(x)` and `math.pow(x,y)` for `math.e ** x` and `x ** y`, respectively in the codebase to avoid any future problems with these functions.

Stop using math.exp and math.pow

---

.github/workflows/mypy.yml

I made some small changes to the mypy gh action to fix some things that have been bugging me a bit
1. The name is now "mypy" instead of "Lint". This makes sense since we already use the Ruff action for linting and mypy is technically used for type checking rather than linting
2. The action is now triggered consistently on all pushes and pull requests like the lint and test actions.
3. The action is no longer tied to the x64 architecture. This means that people using computers with ARM chips (like myself) can now run this action more easily locally. (Before, when I'd run [act](https://github.com/nektos/act), I'd have to run `act --container-architecture linux/amd64`. Now I can just simply run `act`).
4. I also got rid of that secret github token thing since it's not necessary.
5. Etc
Let …

Improve mypy gh action

---

.github/workflows/test.yml
README.md

- I updated our pytest gh action to test multiple versions of python, namely python versions `3.10`, `3.11`, `3.12` and `3.13`.
- I also added a shield to the README to show that python 3.10+ is supported
Let me know if there are any questions!

Test multiple versions of python in pytest gh action

---

fsrs/fsrs.py
tests/test_basic.py

I frequently use the `fsrs` package within jupyter notebooks and would like to be able to more easily see the state of the various fsrs objects I'm working with.
Previously, viewing the state was not straightforward
```python
from fsrs import Card
card = Card()
print(card)
```
The indirect workaround was just to use the object's `to_dict()` method
```python
print(card.to_dict())
```
but this could be made more straight forward by implementing a `__repr__` method to each of the major fsrs classes (currently excluding the `Optimizer` class).
Now with the `__repr__` method, printing the state of the objects is easy.
```python
print(card)
```
I'll note that the `__repr__` method is basically a more general `__str__` method and that `__repr__` will act as a `__str__` method if one is not …

Add __repr__ methods to Card, ReviewLog and Scheduler classes

---

README.md
fsrs/fsrs.py
fsrs/optimizer.py
pyproject.toml
tests/test_basic.py

New `Card` objects, when created, are assigned a `card_id` correpsonding to the current epoch milliseconds of when the card was created. Unfortunately, when cards are created in a batch like
```python
from fsrs import Card
cards = []
for i in range(100):
card = Card()
cards.append(card)
```
there may be `card_id` collisions where two different cards are created within 1ms of eachother and thus incorrectly assigned the same `card_id`.
Currently, to account for this issue, we added a section on batch card creation in the README warning developers to wait `1ms` between creating new `Card` objects to prevent collisions. While this warning may be enough for some, I think that the `card_id` initialization is a bit of a leaky abstraction and could be best solved by preventing collisions on our …

Prevent card id collisions

---

.github/workflows/test.yml
CONTRIBUTING.md
README.md

pytorch v2.6.0 was [released](https://github.com/pytorch/pytorch/releases/tag/v2.6.0) today and is now compatible with python3.13 meaning that python3.13 users can now use py-fsrs's optimizer.
I modified the optimizer github action to verify that the optimizer is now compatible with python3.13 and also updated the README and CONTRIBUTING to stop suggesting installing the optimizer with python3.10-3.12.

Optimizer is now compatible with python3.13

---

README.md
fsrs/optimizer.py
pyproject.toml
tests/test_optimizer.py

I added a `compute_optimal_retention` method to the `Optimizer` class which estimates an optimal `desired_retention` rate for the `Scheduler` by simulating the cost of reviewing cards at various different levels of retention. Specifically, it simulates the following fixed retention rates `[0.7, 0.75, 0.8, 0.85, 0.9, 0.95]` and chooses the most optimal one, basically like a 'grid search'. After much experimentation with Brent's method, I decided that a grid search would be both more efficient and accurate since Brent's method takes longer and unfortunately more frequently gets stuck at local minima given the stochastic (and thus non-convex) nature of the simulations.
I also did the following:
1. Added `pandas` to the optional `optimizer` dependencies
2. Added more unit tests
3. Updated the …

Compute optimal retention

---

fsrs/fsrs.py
pyproject.toml
tests/test_basic.py

It was brought to my attention in #89 that the edge case of a single `Card` being scheduled with multiple `Scheduler` objects with variable numbers of re/learning steps was not being handled correctly and that this was not being picked up because there was an issue with one of the unit tests.
I went and fixed the edge case handling and also fixed the unit test. And then I also bumped the patch from `5.1.0` to `5.1.1`

Fix multiple schedulers edge case

---

fsrs/fsrs.py
pyproject.toml
tests/test_basic.py

Previously, in the edge case where a `Card` in the `Learning` state was scheduled with a new `Scheduler` with fewer `learning_steps` than the `Card`'s current `step`, the `Card` would be moved to the `Review` state after being reviewed, regardless of the chosen rating. 
For example:
```python
from fsrs import Scheduler, Card, Rating
from datetime import timedelta
scheduler_with_three_learning_steps = Scheduler(
learning_steps=(timedelta(minutes=1), timedelta(minutes=5), timedelta(minutes=10))
)
scheduler_with_one_learning_step = Scheduler(
learning_steps=(timedelta(minutes=1),)
)
card = Card()
print(card.state.name)
print(card.step)
card, _ = scheduler_with_three_learning_steps.review_card(card, Rating.Good)
card, _ = scheduler_with_three_learning_steps.review_card(card, Rating.Good) …
```

Fix handling of multiple schedulers edge case

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
SECURITY.md

I was thinking it'd be a good idea to bring py-fsrs up to github's recommended community standards. See [here](https://github.com/open-spaced-repetition/py-fsrs/community).
To do this, I
- Added a code of conduct
- Added a security policy
- Added an issue template when creating new issues
- Added a PR template for new pr's.
Overall, I tried to make these policies and templates pretty minimal so they don't get in the way.
Lmk if you have any questions

Bring Py-FSRS up to recommended community standards

---

fsrs/fsrs.py
pyproject.toml
tests/test_optimizer.py

Closes #95
- I added a new helper method in the scheduler code to clamp a `Card`'s difficulty value between 1.0 and 10.0 based on whether `Card.difficulty` is a `torch.Tensor` or not.
- I also added a new unit test
- And I bumped patch `5.1.2`->`5.1.3`
Lmk if you have any questions 👍

Clamp Card.difficulty differently if it's a tensor

---

fsrs/fsrs.py
pyproject.toml
tests/test_basic.py
tests/test_optimizer.py

Previously, if a `Card` was failed enough times, its `stability` could reach 0. This specically caused problems where the retrievability calculation could result in a division by 0 or even making the value of `stability` 'stuck' at 0 for future attempted stability updates.
To patch this issue, I made it so that, if the next value of `stability` reaches 0, then the `Scheduler` just keeps the previous `stability` value. I also added another unit test and bumped the patch version number.
Lmk if you have any questions

Enforce lower bound on card stability on stability updates

---

.github/workflows/docs.yml
.gitignore
pyproject.toml

Similar to what `ts-fsrs` is doing with [TypeDoc](https://open-spaced-repetition.github.io/ts-fsrs/), I thought it'd be a good idea if py-fsrs also had a documentation page.
For this, I went with [pdoc](https://pdoc.dev/) (made by the same people behind [autofix.ci](https://autofix.ci/)).
Basically how it'd work is, whenever we publish a new (non pre-release) release of py-fsrs, this github action will automatically deploy a new documentation site to this repo's github pages. I also added the `workflow_dispatch` trigger in the action as well so we can manually release new documentation in between publishing releases if we want.
I also added `pdoc` to the optional `dev` dependencies. If you wanna test locally, just run 
```bash
pdoc fsrs --logo …
```

Generate py-fsrs documention and host on Github pages

---

.github/workflows/test.yml
fsrs/fsrs.py
tests/test_basic.py

Previously, the code for the basic `fsrs.py` module wasn't fully covered so I went and added some more unit tests to bring it to full 100% code coverage.
However, with that being said, this package's code is still not yet fully covered since not all of the optimizer code is currently covered. This will be for a future PR.
Additionally, I modified the `test.yml` github action to compute *line* coverage rather than *branch* coverage for now. Line coverage is the default type of coverage and it is also the recommended type of coverage to track when starting out with code coverage according to [this article](https://about.codecov.io/blog/line-or-branch-coverage-which-type-is-right-for-you/). We could move back to branch coverage perhaps once we bring this package to full coverage with the …

Add full code coverage for basic, non-optimizer code

---

fsrs/fsrs.py

Currently, the `Card`, `ReviewLog` and `Scheduler` classes implement custom `__init__`, `__eq__` and `__repr__` methods. However, many of these methods are implemented in such a way that the code can be substituted easily by making the class a `dataclass`.
For example, by simply adding the `@dataclass` decorator to the `ReviewLog` class, we can completely delete its `__init__`, `__repr__` and `__eq__` methods entirely and keep the same behaviour as before. And for the `Card` and `Scheduler` classes, we can use `@dataclass(init=False)` to substitute the `__eq__` and `__repr__` methods but not the `__init__` methods since they use custom logic that we'd like to keep.

Use dataclasses

---

.github/workflows/test.yml
fsrs/__init__.py
pyproject.toml
tests/test_basic.py

Closes #126 
Currently, developers who have installed the optional `[optimizer]` dependency must load the `Optimizer` module (and all of its dependencies) when first importing the `fsrs` package. This creates extra overhead during startup time even when the `Optimizer` module isn't explicitly imported.
For example, a developer who has `fsrs` installed without the optional `[optimizer]` dependencies can execute
```python
from fsrs import Card # (doesn't load torch since optmizer dep not installed)
```
quickly as it will not also load the `Optimizer` dependencies such as `torch`, etc.
However, a developer who has `fsrs` installed with the optional `[optimizer]` dependencies will find that the same
```python
from fsrs import Card # (DOES load torch since optimizer dep installed)
```
takes …

Add lazy loading for the Optimizer module

---

.github/workflows/type-check.yml
CONTRIBUTING.md
README.md
fsrs/__init__.py
fsrs/card.py
fsrs/rating.py
fsrs/review_log.py
fsrs/scheduler.py
fsrs/state.py
pyproject.toml

Closes #99 
We originally removed `mypy` earlier this year in order to make adding the optimizer easier. Now that the optimizer has been implemented, I think we can add `mypy` back.
In this PR, I re-added `mypy` as a dev dependency and configured it to typecheck evertything in the `fsrs/` directory except for `fsrs/optimizer.py`. I also made some changes to the various modules in order to get them to pass `mypy`'s typechecks.
Additionally, I did the following:
1. I moved the `State` and `Rating` enums into their own modules `state.py` and `rating.py`, respectively to keep things more modular
2. I added a new `type-check.yml` github action to run `mypy` in CI
3. and I updated the `README.md` and `CONTRIBUTING.md`
Lmk if you have any questions 👍
--
(also, I still think it'll be a challenge …

Reintroduce mypy

---

README.md

I recently made an [interactive demo](https://interactive-forgetting-curve.streamlit.app/) of py-fsrs and thought I'd add it to the README.
Lmk if you have any questions 👍

Add link to interactive demo of py-fsrs in README

---

README.md
fsrs/scheduler.py
pyproject.toml
tests/test_basic.py

I added a new method `Scheduler.reschedule_card(card: Card, review_logs: list[ReviewLog]) -> Card` which takes a given card and its review logs and reruns it through its review history with the current scheduler.
This method is meant to be used when a developer switches to a new scheduler and would like to update their card's state as if it had always been scheduled by the new scheduler, rather than the old scheduler. This is especially useful for updating cards after the optimizer.
I also added some tests, updated the README and bumped the version from `6.1.1` to `6.2.0`.

Add method for rescheduling cards

---

.github/workflows/type-check.yml
CONTRIBUTING.md
README.md
pyproject.toml

This PR replaces `mypy` with [ty](https://github.com/astral-sh/ty) as py-fsrs's static type checker. `ty` is developed by the same people as `ruff` and `uv`. Even though `ty` is still technically in development, I thought it would be interesting to include in this project - especially as the tool becomes more mature. This PR is also similar to #124 but has been completed.
In sum, I did the following:
1. Replaced `mypy` with `ty` in our optional `dev` dependencies in the `pyproject.toml`
2. Replaced `mypy` with `ty` in our `type-check.yml` gh workflow.
3. Updated the README and CONTRIBUTING to reflect moving from mypy to ty

Replace mypy with ty
